# Generated by Django 2.1a1 on 2018-06-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180626_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='email',
            new_name='max_range',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='min_range',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='file',
            new_name='upload_your_image',
        ),
    ]
