# Generated by Django 2.1a1 on 2018-06-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180627_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='max_range',
            field=models.IntegerField(blank=True, default=999999),
        ),
        migrations.AlterField(
            model_name='data',
            name='min_range',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
