# Generated by Django 2.1a1 on 2018-06-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20180627_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='upload_your_image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
